version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - echo 'Zipping the artifacts'
      - zip ./lambda.zip databasehandler.py
  post_build:
    commands:
      - echo "Updating lambda function .."
      - aws lambda update-function-code --function-name databasehandler --zip-file fileb://lambda.zip
      - echo Build completed on `date`
artifacts:
  files:
    - lambda.zip